title: LachsHub
headerStyle: clean
background:
  image: https://s1.cdn.autoevolution.com/images/news/gallery/stunning-1991-porsche-911-special-commission-reveals-singer-expansion-in-taiwan_1.jpg
  blur: md
  saturate: 50
  brightness: 50
  opacity: 70
theme: dark
color: zinc
useEqualHeights: false
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: true
hideErrors: true
statusStyle: "dot"
layout:
  FavSites:
    iconsOnly: true
    header: false
    style: row
  Arr:
    header: false
    style: row
    columns: 5
  Platform:
    header: false
    style: row
    columns: 3
    Media:
      header: false
      style: row
      Apps:
        header: false
        style: row
        columns: 2
    NAS:
      header: false
      style: row
   